[phases.setup]
nixPkgs = ['nodejs_22', 'pnpm-10_x']

[phases.install]
cmds = ['cd .. && pnpm install --frozen-lockfile']

[phases.build]
cmds = ['cd .. && pnpm --filter=shared build && cd backend && pnpm build']

[start]
cmd = 'cd backend && pnpm start:prod'

[variables]
NODE_ENV = 'production'